backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home Page"
        file: "index.html"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Hero Heading", name: "hero_heading", widget: "string"}
          - {label: "Hero Text", name: "hero_text", widget: "text"}
          
  - name: "videos"
    label: "Videos"
    folder: "_videos"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "YouTube URL", name: "youtube_url", widget: "string"}